sudo: required
services:
  - docker

before_install:
  - docker build -t rickthomas1980/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rickthomas1980/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "Richie's Docker-React App"
  env: "RichiesDocker-ReactApp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-357307979654"
  bucket_path: "Richie's Docker-React App"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
